version: "3.5"

services:
  api01: &api # image: lucianocorreia/rinha-backend-2024-q1:latest
    build:
      context: .
    container_name: api01
    hostname: api01
    environment:
      - PORT=3000
      - DSN=postgresql://postgres:postgres@db:5432/rinha
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"
  api02:
    <<: *api
    container_name: api02
    hostname: api02
    ports:
      - "3001:3000"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rinha"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c max_connections=1000 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "500MB"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "10MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
